name: Demo Run

on:
  workflow_dispatch:

jobs:
  test-summary:
    name: Run Arcana Gate Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./